channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - wheel
  - r-base=4.1
  - r-tidyverse
  - r-spacyr
  - pip:
     - https://huggingface.co/huspacy/hu_core_news_lg/resolve/v3.4.3/hu_core_news_lg-any-py3-none-any.whl
  
